name: flutter_test_app
description: "Flutter Test App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^9.2.2
  get_it: ^8.0.3
  injectable: ^2.5.0
  retrofit: ^4.4.0
  logger: ^2.4.0
  dio: ^5.8.0+1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^9.3.1
  injectable_generator: ^2.7.0
  retrofit_generator: '>=8.0.0 <10.0.0'
  build_runner: ^2.3.3
  json_serializable: ^6.8.0
  freezed: ^3.0.6

flutter:
  uses-material-design: true

